### PR TITLE
Pull Request fo Epoch Admin Tools Test Branch v 1.10.7

### PR DESCRIPTION
**Pull request by worldwidesorrow**
Nox, I am not sure if I am doing this right. I chose to merge my files into your test branch. I am submitting the pull request. Let me know if this is right or if I need to do it differently. I was working on the tools tonight and made a few new additions (mostly keybinds). I can talk to you on the Epoch Discord or a friend's Teamspeak server if you like.

### CODE REVIEW

**Comment by noxsicarius** [comment]
It looks like your modifications may have been done on the master branch instead of the test branch. That means you are missing a lot of the newer code that I created. I would first suggest looking through the files listed as conflicting and see if there is any code you need to copy into yours.

**Comment by worldwidesorrow** [comment]
I figured out what I did wrong. When I forked your github, I did not realize that I was forking all branches. I was mistakenly updating Master as you suggested. I did not see that I could change the branches on my forked copy. Cancel this pull request. I am going to apply my updates to my forked test branch and resubmit.

**Comment by worldwidesorrow** [comment]
I didn't realize I could close this pull request myself.

**Comment by noxsicarius** [comment]
The good thing is once this is all done, your work will be logged in the parent repository and show up in the contributors log.

**Pull request closed without merging**
